### ISSUE TITLE
500 Error with fof/spamblock when marking users as spammer

### ISSUE THREAD

**Issue by dsevillamartin** [ReFlar/StopForumSpam#3]
Occurs in https://discuss.flarum.org.
From https://github.com/FriendsOfFlarum/spamblock/issues/2.

```php
[2018-12-03 23:14:32] production.ERROR: GuzzleHttp\Exception\ServerException: Server error: `GET http://www.stopforumspam.com/add.php?email=<username>%40<domain>.com&$
<p>IP Address and IP Address cannot be added [Local Net]</p>
 in vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object$
#1 vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#7 vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#10 vendor/reflar/stopforumspam/src/Listeners/ReportSpammer.php(49): GuzzleHttp\Client->request('GET', 'http://www.stop...')
```

**Comment by KyrneDev** [comment]
closed w/ f17556a
